### ISSUE TITLE
Canvas check

### ISSUE THREAD

**Issue by ChoyV** [rgalyeon/Scroll_V2#3]
There is a error in your code when you check whether Profile is minted
 
```sh 
minted = await contract.functions.isProfileMinted(self.address).call()
```

You have to getProfile first and then check isProfileMinted

Like this : 

```sh
profile= await contract.functions.getProfile(self.address).call();
minted = await contract.functions.isProfileMinted(profile).call()
```

**Comment by rgalyeon** [comment]
Thank you so much! I really appreciate your help. I couldn't figure out how it worked. I will fix the code soon.
